name: deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - CHANGELOG.md
      - LICENSE
      - ".github/ISSUE_TEMPLATE/**"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Build Number
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Get Build Number
        run: |
          echo $BUILD_NUMBER

      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Kubectl
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Build Docker images
        run: docker-compose build

      - name: Push Docker images
        run: docker-compose push

      - name: Deploy
        run: sh ./deploy/run.sh
